from enum import StrEnum


class FlowStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ARCHIVED = "ARCHIVED"


class RunStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    WAITING_CALLBACK = "WAITING_CALLBACK"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NodeRunStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    WAITING_CALLBACK = "WAITING_CALLBACK"
    RETRY_WAIT = "RETRY_WAIT"
    POLL_WAIT = "POLL_WAIT"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


NODE_TERMINAL_STATUSES = {
    NodeRunStatus.SUCCESS,
    NodeRunStatus.FAILED,
    NodeRunStatus.SKIPPED,
    NodeRunStatus.CANCELLED,
}


class RunTriggerType(StrEnum):
    MANUAL = "MANUAL"
    SCHEDULE = "SCHEDULE"
    RERUN = "RERUN"


class GroupRole(StrEnum):
    GROUP_ADMIN = "GROUP_ADMIN"
    FLOW_DESIGNER = "FLOW_DESIGNER"
    FLOW_EXECUTOR = "FLOW_EXECUTOR"
    APPROVER = "APPROVER"
    VIEWER = "VIEWER"


class ApprovalTaskStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"
